import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import Button from '../../components/common/Button'
import Toast from '../../components/common/Toast'
import useAuth from '../../hooks/useAuth'
export default function Login() { const { login } = useAuth(); const navigate=useNavigate(); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 async function submit(event){event.preventDefault();setBusy(true);setError('');try{const user=await login(Object.fromEntries(new FormData(event.currentTarget)));navigate(user.role==='admin'?'/admin/dashboard':'/user/home',{replace:true})}catch(err){setError(err.response?.data?.message||'Unable to sign in')}finally{setBusy(false)}}
 return <main className="grid min-h-screen place-items-center bg-slate-100 p-4"><section className="w-full max-w-md rounded-3xl border bg-white p-8 shadow-sm"><Link to="/login" className="text-xl font-black tracking-tight text-emerald-900">Product<span className="text-amber-500">.</span></Link><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Welcome back</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Sign in to your account</h1><p className="mt-2 text-sm text-slate-500">Use your account to continue to the product store.</p><form className="mt-7 space-y-5" onSubmit={submit}><label className="block text-sm font-medium">Email<input name="email" type="email" autoComplete="email" required className="mt-2 w-full rounded-xl border px-3 py-3 outline-none focus:border-emerald-700"/></label><label className="block text-sm font-medium">Password<input name="password" type="password" autoComplete="current-password" required className="mt-2 w-full rounded-xl border px-3 py-3 outline-none focus:border-emerald-700"/></label><Button className="w-full" disabled={busy}>{busy?'Signing in…':'Login'}</Button></form><p className="mt-6 text-center text-sm text-slate-500">Don't have an account? <Link className="font-semibold text-emerald-800 hover:underline" to="/register">Create an account</Link></p></section><Toast message={error}/></main>
}
