import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import Button from '../../components/common/Button'
import Toast from '../../components/common/Toast'
import useAuth from '../../hooks/useAuth'
import { validateRegistration } from '../../utils/validation'
export default function Register() { const { register }=useAuth();const navigate=useNavigate();const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 async function submit(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));const validationError=validateRegistration(data);if(validationError){setError(validationError);return}setBusy(true);setError('');try{await register({name:data.name,email:data.email,password:data.password});navigate('/login',{state:{message:'Account created. Please sign in.'}})}catch(err){setError(err.response?.data?.message||'Unable to create account')}finally{setBusy(false)}}
 return <main className="grid min-h-screen place-items-center bg-slate-100 p-4"><section className="w-full max-w-md rounded-3xl border bg-white p-8 shadow-sm"><Link to="/login" className="text-xl font-black tracking-tight text-emerald-900">Product<span className="text-amber-500">.</span></Link><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Customer account</p><h1 className="mt-2 text-3xl font-bold">Create your account</h1><form className="mt-6 space-y-4" onSubmit={submit}><label className="block text-sm font-medium">Name<input name="name" autoComplete="name" required className="mt-2 w-full rounded-xl border px-3 py-3"/></label><label className="block text-sm font-medium">Email<input name="email" type="email" autoComplete="email" required className="mt-2 w-full rounded-xl border px-3 py-3"/></label><label className="block text-sm font-medium">Password<input name="password" type="password" minLength="6" autoComplete="new-password" required className="mt-2 w-full rounded-xl border px-3 py-3"/></label><label className="block text-sm font-medium">Confirm password<input name="confirmPassword" type="password" minLength="6" autoComplete="new-password" required className="mt-2 w-full rounded-xl border px-3 py-3"/></label><Button className="w-full" disabled={busy}>{busy?'Creating…':'Register'}</Button></form><p className="mt-5 text-center text-sm text-slate-500">Already registered? <Link className="font-semibold text-emerald-800" to="/login">Login</Link></p></section><Toast message={error}/></main>
}

