import { useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import { FiPlus } from 'react-icons/fi'
import baseUrl from '../../services/baseUrl'
import commonApi from '../../services/commonApi'
import allApi from '../../services/allApi'
import ProductTable from '../../components/ProductTable'
import SearchFilter from '../../components/SearchFilter'
import DeleteModal from '../../components/DeleteModal'
const authHeader=()=>({Authorization:`Bearer ${localStorage.getItem('token')}`})
export default function Products(){const [products,setProducts]=useState([]),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState(''),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[sort,setSort]=useState('newest'),[selected,setSelected]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[deleting,setDeleting]=useState(false);async function load(){setLoading(true);try{const params=new URLSearchParams();if(search)params.set('search',search);if(category)params.set('category',category);if(minPrice)params.set('minPrice',minPrice);if(maxPrice)params.set('maxPrice',maxPrice);if(sort)params.set('sort',sort);const suffix=params.toString()?`?${params}`:'';const res=await commonApi('GET',baseUrl+allApi.getProductsApi+suffix,'',authHeader());setProducts(res.data)}catch(e){setError(e.response?.data?.message||'Could not load products')}finally{setLoading(false)}}useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[search,category,minPrice,maxPrice,sort]);const categories=useMemo(()=>[...new Set(products.map(p=>p.category).filter(Boolean))],[products]);const visible=products.filter(p=>status===''||(status==='in'?Number(p.stock)>0:Number(p.stock)<=0));async function confirmDelete(){setDeleting(true);try{await commonApi('DELETE',baseUrl+allApi.deleteProductApi+'/'+selected._id,'',authHeader());setSelected(null);await load()}catch(e){setError(e.response?.data?.message||'Could not delete product')}finally{setDeleting(false)}}return <section><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Catalogue</p><h1 className="mt-1 text-3xl font-bold">Products</h1></div><Link to="/admin/products/add" className="flex items-center gap-2 rounded-xl bg-emerald-800 px-4 py-3 text-sm font-semibold text-white"><FiPlus/>Add product</Link></div><div className="mb-5"><SearchFilter search={search} onSearch={setSearch} category={category} onCategory={setCategory} categories={categories} status={status} onStatus={setStatus} sort={sort} onSort={setSort} minPrice={minPrice} maxPrice={maxPrice} onMinPrice={setMinPrice} onMaxPrice={setMaxPrice}/></div>{error&&<p className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{loading?<p className="py-14 text-center text-slate-500">Loading products…</p>:visible.length?<ProductTable products={visible} onDelete={setSelected}/>:<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-slate-500">No products match these filters.</div>}<DeleteModal product={selected} onCancel={()=>setSelected(null)} onConfirm={confirmDelete} loading={deleting}/></section>}
